package lib

func GetAnomalyMap(version int) map[string]string {
    var anomalyMap map[string]string
    switch version {
    case 1:
        anomalyMap = map[string]string{
            "AFS_ALARM_ALARM":           "AFS_ALARM_ALARM",
            "AFS_GROUND_ALARM":          "AFS_GROUND_ALARM",
            "AFS_I_FAULT_FULL":          "FAULT_CURRENT",
            "AFS_I_FAULT_TEMP":          "TEMP_FAULT_CURRENT",
            "BKR_CLOSE":                 "BKR_CLOSE",
            "BKR_FAIL_TO_OPR":           "BKR_FAIL_TO_OPR",
            "BKR_OPEN":                  "BKR_OPEN",
            "CURRENT_LIMIT":             "CURRENT_LIMIT",
            "FAULT_ALARM":               "FAULT_ALARM",
            "FAULT_CURRENT":             "FAULT_CURRENT",
            "FCI_FAULT_ALARM":           "FAULT_ALARM",
            "FCI_I_FAULT_FULL":          "FAULT_CURRENT",
            "FCI_I_FAULT_TEMP":          "TEMP_FAULT_CURRENT",
            "FC_NO_BO":                  "FC_NO_BO",
            "FDRHD_DE_ENERGIZED":        "FDRHD_DE_ENERGIZED",
            "FDRHD_ENERGIZED":           "FDRHD_ENERGIZED",
            "HIGH_VOLTAGE":              "HIGH_VOLTAGE",
            "INTELI_OPS_DSW_CLOSE":      "INTELI_OPS_DSW_CLOSE",
            "INTELI_OPS_DSW_OPEN":       "INTELI_OPS_DSW_OPEN",
            "INTELI_PH_ALARM":           "INTELI_PH_ALARM",
            "LATERAL_OUTAGES":           "LATERAL_OUTAGES",
            "LG_PD_10_V2":               "LG_PD_10",
            "PF_SPIKES_V3":              "PF_SPIKES",
            "REGULATOR_BLOCK":           "REGULATOR_BLOCK",
            "RE_FUSE_ONLY":              "RE_FUSE_ONLY",
            "TEMP_FAULT_CURRENT":        "TEMP_FAULT_CURRENT",
            "THD_SPIKES_V3":             "THD_SPIKES",
            "VOLTAGE_DROP":              "VOLTAGE_DROP",
            "ZERO_CURRENT_V4":           "ZERO_CURRENT",
            "ZERO_POWER_V4":             "ZERO_POWER",
            "ZERO_VOLTAGE_V4":           "ZERO_VOLTAGE",
            "FDRHD_CURRENT_LIMIT":       "CURRENT_LIMIT",
            "FEEDER_CURRENT_LIMIT":      "CURRENT_LIMIT",
            "INTELI_CURRENT_LIMIT":      "CURRENT_LIMIT",
            "INTELI_FAULT_CURRENT":      "FAULT_CURRENT",
            "FDRHD_HIGH_VOLTAGE":        "HIGH_VOLTAGE",
            "FEEDER_HIGH_VOLTAGE":       "HIGH_VOLTAGE",
            "INTELI_HIGH_VOLTAGE":       "HIGH_VOLTAGE",
            "INTELI_TEMP_FAULT_CURRENT": "TEMP_FAULT_CURRENT",
            "FDRHD_VOLTAGE_DROP":        "VOLTAGE_DROP",
            "FEEDER_VOLTAGE_DROP":       "VOLTAGE_DROP",
            "INTELI_VOLTAGE_DROP":       "VOLTAGE_DROP",
        }
    case 2:
        anomalyMap = map[string]string{
            "AFS_I_FAULT_FULL":          "FEEDER_FAULT",
            "AFS_I_FAULT_TEMP":          "FEEDER_TEMP_FAULT",
            "BKR_CLOSE":                 "BKR_CLOSE",
            "BKR_OPEN":                  "BKR_OPEN",
            "FAULT_ALARM":               "SUBSTATION_FAULT",
            "FAULT_CURRENT":             "SUBSTATION_FAULT",
            "FCI_FAULT_ALARM":           "FEEDER_FAULT",
            "FCI_I_FAULT_FULL":          "FEEDER_FAULT",
            "FCI_I_FAULT_TEMP":          "FEEDER_TEMP_FAULT",
            "FDRHD_CURRENT_LIMIT":       "CURRENT_LIMIT",
            "FDRHD_HIGH_VOLTAGE":        "HIGH_VOLTAGE",
            "FDRHD_VOLTAGE_DROP":        "VOLTAGE_DROP",
            "FEEDER_CURRENT_LIMIT":      "CURRENT_LIMIT",
            "FEEDER_HIGH_VOLTAGE":       "HIGH_VOLTAGE",
            "FEEDER_VOLTAGE_DROP":       "VOLTAGE_DROP",
            "INTELI_FAULT_CURRENT":      "FEEDER_FAULT",
            "INTELI_HIGH_VOLTAGE":       "INTELI_HIGH_VOLTAGE",
            "INTELI_TEMP_FAULT_CURRENT": "FEEDER_TEMP_FAULT",
            "INTELI_VOLTAGE_DROP":       "INTELI_VOLTAGE_DROP",
            "LG_PD_10_V2":               "LG_PD_10",
            "PF_SPIKES_V3":              "PF_SPIKES",
            "REGULATOR_BLOCK":           "REGULATOR_BLOCK",
            "TEMP_FAULT_CURRENT":        "SUBSTATION_TEMP_FAULT",
            "THD_SPIKES_V3":             "THD_SPIKES",
            "ZERO_CURRENT_V4":           "ZERO_RULE",
            "ZERO_POWER_V4":             "ZERO_RULE",
            "ZERO_VOLTAGE_V4":           "ZERO_RULE",
        }
    case 3:
        anomalyMap = map[string]string{
            "AFS_ALARM_ALARM":           "FEEDER_FAULT",
            "AFS_GROUND_ALARM":          "FEEDER_FAULT",
            "AFS_I_FAULT_FULL":          "FEEDER_FAULT",
            "AFS_I_FAULT_TEMP":          "FEEDER_FAULT",
            "INTELI_OPS_DSW_CLOSE":      "INTELI_CLOSE",
            "INTELI_OPS_DSW_OPEN":       "INTELI_OPEN",
            "INTELI_PH_ALARM":           "FEEDER_FAULT",
            "INTELI_CURRENT_LIMIT":      "CURRENT_LIMIT",
            "INTELI_FAULT_CURRENT":      "FEEDER_FAULT",
            "INTELI_HIGH_VOLTAGE":       "HIGH_VOLTAGE",
            "INTELI_TEMP_FAULT_CURRENT": "FEEDER_FAULT",
            "INTELI_VOLTAGE_DROP":       "VOLTAGE_DROP",
            "FCI_FAULT_ALARM":           "FEEDER_FAULT",
            "FCI_I_FAULT_FULL":          "FEEDER_FAULT",
            "FCI_I_FAULT_TEMP":          "FEEDER_FAULT",
            "FAULT_ALARM":               "SUBSTATION_FAULT",
            "FAULT_CURRENT":             "SUBSTATION_FAULT",
            "TEMP_FAULT_CURRENT":        "SUBSTATION_FAULT",
            "BKR_CLOSE":                 "BKR_CLOSE",
            "BKR_OPEN":                  "BKR_OPEN",
            "CURRENT_LIMIT":             "CURRENT_LIMIT",
            "HIGH_VOLTAGE":              "HIGH_VOLTAGE",
            "PF_SPIKES_V3":              "PF_SPIKES",
            "THD_SPIKES_V3":             "THD_SPIKES",
            "VOLTAGE_DROP":              "VOLTAGE_DROP",
            "ZERO_CURRENT_V4":           "ZERO_RULE",
            "ZERO_POWER_V4":             "ZERO_RULE",
            "ZERO_VOLTAGE_V4":           "ZERO_RULE",
            "FDRHD_CURRENT_LIMIT":       "CURRENT_LIMIT",
            "FEEDER_CURRENT_LIMIT":      "CURRENT_LIMIT",
            "FDRHD_HIGH_VOLTAGE":        "HIGH_VOLTAGE",
            "FEEDER_HIGH_VOLTAGE":       "HIGH_VOLTAGE",
            "FDRHD_VOLTAGE_DROP":        "VOLTAGE_DROP",
            "FEEDER_VOLTAGE_DROP":       "VOLTAGE_DROP",
            "LG_PD_10_V2":               "LG_PD_10",
        }

    }
    return anomalyMap
}
